[theme]
base = "light"
primaryColor         = "#1A56DB"
font                 = "sans serif"

[server]
headless             = true
enableCORS           = false
enableXsrfProtection = false

[browser]
gatherUsageStats     = false
